In [ ]:
#WAP to create a single dimential array and display the elements in it as a glance or individually.

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(a)
print(a[a>3])

[1 2 3 4 5]
[4 5]


In [30]:
#WAP to perform the statistacial function (Mean, median, veriance, standard deviation) & all the algebric operation (add, substact,multiply, exponent, min, max) 


print("Mean of the array", np.mean(a))
print("Median of the array", np.median(a))
print("Varience of the array", np.var(a))
print("Standard deviation of the array", np.std(a))
print("Sum of the two array", np.add(a,b))
print("Difference of the two array", np.subtract(a,b))
print("Product of the two array", np.dot(a,b))
print("Exponential of the array", (a ** 3))
print("Min of the two array", np.min(a))
print("Max of the two array", np.max(b))

Mean of the array 3.0
Median of the array 3.0
Varience of the array 2.0
Standard deviation of the array 1.4142135623730951
Sum of the two array [ 7  9 11 13 15]
Difference of the two array [-5 -5 -5 -5 -5]
Product of the two array 130
Exponential of the array [  1   8  27  64 125]
Min of the two array 1
Max of the two array 10


In [37]:
#WAP to create a matrix and perform the following operation on it - Addition, multiplication, transpose, determinant and inverse

c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

d = np.array([[11, 12, 13],
              [14, 15, 16],
              [17, 18, 19]])

print("Sum of two matrix :", np.add(c,d))
print("Multiplication of two matrix :", np.dot(c, d))
print("Determinant of matrix :", np.linalg.det(c))
print("Inverse of matrix :", np.linalg.inv(c))
print("Tranpose of matrix :", np.transpose(c))

Sum of two matrix : [[12 14 16]
 [18 20 22]
 [24 26 28]]
Multiplication of two matrix : [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Determinant of matrix : 6.66133814775094e-16
Inverse of matrix : [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
Tranpose of matrix : [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
import numpy as np

def display_menu():
    print("\nMatrix Operations Menu")
    print("1. Add Matrices")
    print("2. Multiply Matrices")
    print("3. Determinant of Matrix")
    print("4. Inverse of Matrix")
    print("5. Transpose of Matrix")
    print("6. Exit")

def get_matrix_input():
    while True:
        try:
            rows = int(input("Enter number of rows: "))
            cols = int(input("Enter number of columns: "))
            matrix = []
            print(f"Enter values for a {rows}x{cols} matrix:")
            for i in range(rows):
                row = list(map(int, input(f"Enter row {i+1}: ").split()))
                if len(row) != cols:
                    raise ValueError(f"Row {i+1} must have exactly {cols} values.")
                matrix.append(row)
            return np.array(matrix)
        except ValueError as e:
            print("Invalid input. Please try again.", e)

def main():
    print("Matrix Operations Program")

    # Get matrices from the user
    a = get_matrix_input()
    print("\nMatrix A:")
    print(a)

    b = get_matrix_input()
    print("\nMatrix B:")
    print(b)

    while True:
        display_menu()
        choice = input("Choose an option (1-6): ")

        if choice == '1':
            if a.shape == b.shape:
                print("\nSum of matrices:\n", np.add(a, b))
            else:
                print("Error: Matrices must have the same shape for addition.")

        elif choice == '2':
            if a.shape[1] == b.shape[0]:
                print("\nMultiplication of matrices:\n", np.dot(a, b))
            else:
                print("Error: Number of columns of A must be equal to number of rows of B for multiplication.")

        elif choice == '3':
            if a.shape[0] == a.shape[1]:
                print("\nDeterminant of matrix A:", np.linalg.det(a))
            else:
                print("Error: Determinant can only be calculated for square matrices.")

        elif choice == '4':
            if a.shape[0] == a.shape[1]:
                try:
                    print("\nInverse of matrix A:\n", np.linalg.inv(a))
                except np.linalg.LinAlgError:
                    print("Matrix A is singular, cannot compute inverse.")
            else:
                print("Error: Inverse can only be calculated for square matrices.")

        elif choice == '5':
            print("\nTranspose of matrix A:\n", np.transpose(a))

        elif choice == '6':
            print("Exiting...")
            break

        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

Matrix Operations Program
Enter values for a 3x3 matrix:

Matrix A:
[[1 2 3]
 [3 4 5]
 [5 6 7]]
Invalid input. Please try again. invalid literal for int() with base 10: '6 7 8'
Invalid input. Please try again. invalid literal for int() with base 10: '9 8 7'
Invalid input. Please try again. invalid literal for int() with base 10: '6 5 4'
Enter values for a 3x3 matrix:

Matrix B:
[[1 4 5]
 [7 8 9]
 [4 6 3]]

Matrix Operations Menu
1. Add Matrices
2. Multiply Matrices
3. Determinant of Matrix
4. Inverse of Matrix
5. Transpose of Matrix
6. Exit

Sum of matrices:
 [[ 2  6  8]
 [10 12 14]
 [ 9 12 10]]

Matrix Operations Menu
1. Add Matrices
2. Multiply Matrices
3. Determinant of Matrix
4. Inverse of Matrix
5. Transpose of Matrix
6. Exit

Determinant of matrix A: -4.4408920985006143e-16

Matrix Operations Menu
1. Add Matrices
2. Multiply Matrices
3. Determinant of Matrix
4. Inverse of Matrix
5. Transpose of Matrix
6. Exit

Determinant of matrix A: -4.4408920985006143e-16

Matrix Operations Me